Release/1.0.0
bentonam/fakeit pull request #124
Opened 2017-02-13 23:04 UTC by tjbenton

2017-02-15 17:36 UTC, bentonam commented on app/cli.js
> +export default async function() {
missing docs comments

2017-02-15 17:41 UTC, bentonam commented on app/logger.js
> +      console.log(arg);
Remove this console.log

2017-02-15 17:42 UTC, bentonam commented on app/models.js
> +  // console.log('models.parseModelFunctions');
remove this line

2017-02-15 17:43 UTC, bentonam commented on app/models.js
> +  // console.log('models.parseModelReferences');
remove this line

2017-02-15 17:43 UTC, bentonam commented on app/models.js
> +  // console.log('models.parseModel_properties');
remove this line

2017-02-15 17:43 UTC, bentonam commented on app/models.js
> +    // console.log(type_path);
remove this line

2017-02-15 17:44 UTC, bentonam requested changes
Remove a few console.log's and commented code

2017-02-15 23:29 UTC, tjbenton commented on app/logger.js
> +      console.log(arg);
required to log stuff to the console

2017-02-15 23:31 UTC, tjbenton commented on app/models.js
> +  // console.log('models.parseModelFunctions');
done

2017-02-15 23:31 UTC, tjbenton commented on app/models.js
> +  // console.log('models.parseModelReferences');
done

2017-02-15 23:31 UTC, tjbenton commented on app/models.js
> +  // console.log('models.parseModel_properties');
done

2017-02-15 23:31 UTC, tjbenton commented on app/models.js
> +    // console.log(type_path);
done

2017-02-15 23:32 UTC, tjbenton commented on app/cli.js
> +export default async function() {
done

2017-02-16 00:42 UTC, bentonam approved these changes

2017-02-16 00:42 UTC, merged